Repository jenkins-x/prow-config, pull requests merged in 2018-11, with the labels that each got.

#95 chore: reduce sinker max age to 4h
  prow/config.yaml
Labels: size/XS

#96 feat: add cloudbees-apps to updatebot approved
  prow/config.yaml
Labels: size/XS

#97 disable auto upgardes until we switch to new addons upgrader
  prow/config.yaml
Labels: size/S

#98 try and fix missing branch protection for tide
  prow/config.yaml
Labels: size/M

#99 chore: add policy-engine
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#103 switch from using teh old Jenkins service account to the new knative bot
  prow/config.yaml
Labels: size/L

#105 fix in Tide section config.yaml
  prow/config.yaml
Labels: size/XS

#106 chore: add jx-app-grafana
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#110 chore: add jx-app-gitea
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#113 fix: need to use jenkinsfile for build
  prow/config.yaml
Labels: size/S

#114 fix: split out apps as they need different builds
  prow/config.yaml
Labels: size/S
