Repository jenkins-x/prow-config, pull requests merged in 2018-10, with the labels that each got.

#21 ensure old static Jenkins X jobs pass before auto merging
  prow/config.yaml
Labels: size/XS

#22 enable serverless jenkins CI pipeline on jx
  prow/config.yaml
Labels: size/L

#23 fix jx release
  prow/config.yaml
Labels: size/XS

#24 fix jx CI
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#25 increase builder pod resources
  prow/config.yaml
Labels: size/S

#26 increase builder pod resources
  prow/config.yaml
Labels: size/XS

#27 increase builder pod resources
  prow/config.yaml
Labels: size/XS

#30 latest updates
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#31 increase pod GC so we keep build logs around for a day
  prow/config.yaml
Labels: size/XS

#32 Added configuration to build serverless images
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#33 Corrected docker image for serverless build
  prow/config.yaml
Labels: size/XS

#34 try and trigger jenkins-x/jenkins-x-serverless
  prow/plugins.yaml
Labels: size/XS

#35 add jenkins-x-charts/vault-operator
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#36 fix config
  prow/config.yaml
Labels: size/S

#37 added jenkins-x-builder project
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#38 use a sub path so helm lint works as chart name needs to match checkout out dir
  prow/config.yaml
Labels: size/XS

#40 switch to using full base image to get creds
  prow/config.yaml
Labels: size/XS

#43 switch vault-operator to reference knative build template
  prow/config.yaml
Labels: size/M

#44 add branch protection for charts org
  prow/config.yaml
Labels: size/XS

#45 move remaining pre and post submit configs to use knative build templates
  prow/config.yaml
Labels: size/L

#46 add dex
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#47 fix error unmarshaling /etc/config/config.yaml: error unmarshaling JSON: json: cannot unmarshal number into Go value of type string
  prow/config.yaml
Labels: size/XS

#48 revert to non build templates as we are missing enriched ENVARS like BRANCH_NAME
  prow/config.yaml
Labels: size/L

#49 enable ci + cd for dex again
  prow/config.yaml
Labels: size/S

#50 enable tide for dex
  prow/config.yaml
Labels: size/XS

#53 add ext-java-code-quality
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#55 switch all Jenkins X repos over to prow
  prow/config.yaml
  prow/plugins.yaml
Labels: size/XL

#56 add branch protection to all repos
  prow/config.yaml
Labels: size/M

#60 readme
  README.md
Labels: size/XS

#61 update values to trigger configmap reset
  prow/config.yaml
  prow/plugins.yaml
Labels: size/XS

#62 ensure initial close uses git creds for private repos
  prow/config.yaml
Labels: size/XS

#65 fix knative related contexts so tide can merge
  prow/config.yaml
Labels: size/XS

#67 feat: add haha
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#68 fix ext-spotbugs release job
  prow/config.yaml
Labels: size/XS

#70 lets test auto upgrading prow after a release
  prow/config.yaml
Labels: size/S

#71 add downstream job to test repo
  prow/config.yaml
Labels: size/S

#72 switch update to periodic
  prow/config.yaml
Labels: size/S

#73 avoid periodic until deploy jobs works
  prow/config.yaml
Labels: size/S

#74 rename cdx -> core
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S

#75 update all addons periodically
  prow/config.yaml
Labels: size/S

#76 merge updatebot PRs
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#78 switch tide to match on org
  prow/config.yaml
Labels: size/XS

#79 fix: switched the trusted org from kubernetes to jenkins-x
  prow/plugins.yaml
Labels: size/XS

#80 try to fix tide error matching branch protection strategies
  prow/config.yaml
Labels: size/M

#81 feat: allowing tide to merge 'jenkins-x-chart' repos
  prow/config.yaml
Labels: size/XS

#82 lets drop the tide sync time
  prow/config.yaml
Labels: size/XS

#83 enable triggers for cloudbees repos
  prow/config.yaml
  prow/plugins.yaml
Labels: size/XS

#86 restrict updatebot tide merge config to repos rather than all of org
  prow/config.yaml
Labels: size/XS

#87 chore: enable builds for cloudbees/haha
  prow/config.yaml
Labels: size/M

#88 chore: update plugins for cloudbees/haha
  prow/plugins.yaml
Labels: size/XS

#92 fix: updated tide url to be core.jx...
  prow/config.yaml
Labels: size/XS

#93 chore: decrease upgrade interval from 5m to 15m
  prow/config.yaml
Labels: size/XS
