Repository jenkins-x/prow-config, pull requests merged in 2018-12, with the labels that each got.

#116 add cat plugin to jx-resources to test webhooks
  prow/plugins.yaml
Labels: size/XS

#117 lets try the label plugin on jx
  prow/plugins.yaml
Labels: size/XS

#118 enable lgtm plugin on core-backend
  prow/plugins.yaml
Labels: size/XS

#119 fix: lets switch to use the knative build release script for this repo
  .gitignore
  prow/config.yaml
Labels: size/XS

#120 fix: switch to using knative ci script
  prow/config.yaml
Labels: size/XS

#121 feat: add cb-app-slack
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#122 add CI for cloudbees/policy-tests
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#125 feat: require percy to pass for core-frontend
  prow/config.yaml
Labels: size/XS

#126 chore: removing percy context from core-frontend
  prow/config.yaml
Labels: size/XS

#127 feat: added extra nodocker build for jenkins-x-builders
  prow/config.yaml
Labels: size/S
