Repository jenkins-x/prow-config, pull requests merged in 2019-01, with the labels that each got.

#130 lets reset our prod config using a dummy commit
  README.md
  prow/config.yaml
  prow/plugins.yaml
Labels: size/XS

#129 Remove policy-engine from jenkins-x prod cluster
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#132 fix: add more fixes for prow-config and jenkins-x-images
  prow/config.yaml
Labels: size/S

#134 fix: add repo jx-quickstarts-bdd-test-job
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S

#136 add the allure image
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#137 use bdd build template
  prow/config.yaml
Labels: size/XS

#142 fix: remove sticky team, not needed
  prow/plugins.yaml
Labels: size/XS

#144 Revert "chore: add build for Athens chart"
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#149 knative-build-pipeline chart lives in the root dir
  prow/config.yaml
Labels: size/XS

#150 knative-build-pipeline chart now lives in the knative-build-pipeline dir
  prow/config.yaml
Labels: size/XS

#152 Jacoco app rename and move from jenkins-x org to jenkins-x-apps org.
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#153 Completely missed the postsubmit step for jacoco
  prow/config.yaml
Labels: size/S

#154 chore: lets try add a CI pipeline script
  prow/config.yaml
Labels: size/S

#155 chore: try switch to simpler builder
  prow/config.yaml
Labels: size/S

#158 Added jenkins-x-serverless-filerunner repo
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#159 feat: switching serverless build from cwp to go
  prow/config.yaml
Labels: size/XS

#156 chore: add cloudbees/core-controllers repository.
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#160 Remove policy-tests repository
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M
