Repository jenkins-x/prow-config, pull requests merged in 2019-02, with the labels that each got.

#161 remove deprecated attribute and force self approve
  prow/plugins.yaml
Labels: size/S

#165 fix: removed extra builder from jenkins-x-builders
  prow/config.yaml
Labels: size/S

#166 enable cat and dog plugins for jx
  prow/plugins.yaml
Labels: size/XS

#167 adding jenkins-x-builders-base-image repo
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#169 Enable auto merge for jenkins-x-versions
  prow/config.yaml
Labels: size/XS

#171 lets remove jenkins-x-versions
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#173 rename build pipeline to tekton
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S
